name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  check_composer:
    name: Check composer.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.1'
      - run: composer validate --strict --no-check-lock

  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.2'
      - name: Install dependencies
        run: composer update --ansi --no-progress --prefer-dist --no-interaction
      - run: vendor/bin/phpstan analyze

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]
        browser: [ 'firefox', 'chrome' ]
        selenium: [ '2.53.1', '3', '4' ]
        include:
          - php: '7.4'
            browser: 'edge'
            selenium: '4'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Selenium
        run: |
          mkdir -p ./logs
          SELENIUM_IMAGE=selenium/standalone-${{ matrix.browser }}:${{ matrix.selenium }} docker compose up --no-color &> ./logs/selenium.log &

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "xdebug"
          php-version: "${{ matrix.php }}"
          ini-file: development

      - name: Install dependencies
        run: |
          composer update --no-interaction --prefer-dist --ansi --no-progress

      - name: Wait for selenium to start
        run: |
          curl --head -X GET --silent --show-error --retry 60 --retry-connrefused --retry-delay 1 --max-time 10 http://172.18.0.2:4444

      - name: Run tests
        env:
          SELENIUM_VERSION: ${{ matrix.selenium }}
          DRIVER_URL: http://172.18.0.2:4444/wd/hub
          WEB_FIXTURES_HOST: http://host.docker.internal:8002
          WEB_FIXTURES_BROWSER: ${{ matrix.browser }}
          DRIVER_MACHINE_BASE_PATH: /fixtures/
        run: |
          vendor/bin/phpunit -v --coverage-clover=coverage.xml --colors=always --testdox

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        # See https://github.com/nektos/act#skipping-steps
        if: ${{ !env.ACT }}
        with:
          files: coverage.xml

      - name: Archive logs artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs_php-${{ matrix.php }}_selenium-${{ matrix.selenium }}_${{ matrix.browser }}
          path: logs
