name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  check_composer:
    name: Check composer.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.1'
      - run: composer validate --strict --no-check-lock

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "xdebug"
          php-version: "${{ matrix.php }}"
          ini-file: development

      - name: Install dependencies
        run: |
          composer update --no-interaction --prefer-dist

      - name: Run tests
        run: |
          vendor/bin/phpunit -v --coverage-clover=coverage.xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml

      - name: Archive logs artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: logs_php-${{ matrix.php }}
          path: |
            logs
